@baseUrl = {{$dotenv BASE_URL}}

POST {{baseUrl}}/v1/posts HTTP/1.1
Content-Type: application/json

{
  "title": "string",
  "content": "string"
}

###

GET {{baseUrl}}/v1/posts HTTP/1.1

###

GET {{baseUrl}}/v1/posts/bHp184r9uCUY8fXtMtkk HTTP/1.1