@baseUrl = {{$dotenv BASE_URL}}


### Hello, world!
GET {{baseUrl}}/ HTTP/1.1

### 새 게시물 생성
POST {{baseUrl}}/v1/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "bHp184r9uCUY8fXtMtkk",
  "playlistId": "playlist123",
  "content": "게시물1"
}

### 모든 게시물 
GET {{baseUrl}}/v1/posts HTTP/1.1


### 특정 사용자의 게시물
GET {{baseUrl}}/v1/posts/bHp184r9uCUY8fXtMtkk HTTP/1.1

### ------------------------------

### 새 플레이리스트 생성
POST {{baseUrl}}/v1/playlists HTTP/1.1
Content-Type: application/json

{
  "userId": "user123",
  "title": "My Awesome Playlist",
  "description": "This is a test playlist",
  "isPublic": true,
  "videos": ["video1Url", "video2URL", "video3URL"]
}

### 모든 플레이리스트 
GET {{baseUrl}}/v1/playlists HTTP/1.1

### 특정 플레이리스트 아이디
GET {{baseUrl}}/v1/playlists/Fdpk6YOi4d8djfGfWM8v HTTP/1.1

### 특정 사용자의 플레이리스트
GET {{baseUrl}}/v1/playlists/user/user123 HTTP/1.1

### 플레이리스트 수정

PUT {{baseUrl}}/v1/playlists/Fdpk6YOi4d8djfGfWM8v HTTP/1.1
Content-Type: application/json

{
  "title": "My Awesome Playlist234",
  "userId": "user124",
  "description": "This is a test playlist",
  "isPublic": true,
  "videos": ["video1Url", "video2URL", "video3URL"]
}


### 플레이리스트 삭제
DELETE {{baseUrl}}/v1/playlists/Fdpk6YOi4d8djfGfWM8v HTTP/1.1
Content-Type: application/json

{
  "userId": "user124"
}