export const PATH = {
  HOME: '/',
  SEARCH: '/search',
  ADD_POST: '/post/add',
  SELECT_PLI: '/post/add/selectPli',
  ADD_VIDEOS: '/addVideos',
  PLAYLIST: '/playlist',
  ADD_VIDEO_SELECT_PLI: '/playlist/selectPli',
  PROFILE: '/profile/:userId',
  PROFILE_EDIT: '/profile/:userId/edit',
  SIGN_IN: '/signin',
  SETTINGS: '/settings',
  FOLLOW: '/profile/:userId/follow',
  PRIVACY_POLICY: '/privacyPolicy',
  TERM_OF_SERVICE: '/termOfService',
  COMMENT: '/comment',
} as const;
